FetchReachDense-v4:
  n_timesteps: 60000
  policy: MultiInputPolicy
  noise_type: ornstein-uhlenbeck
  noise_std: 0.37169319553029
  gradient_steps: 1
  train_freq: 1
  learning_rate: 0.0010108124085550568
  batch_size: 256
  policy_kwargs: dict(net_arch=[400, 300])
