FetchReachDense-v4:
  n_timesteps: 1000
  policy: MultiInputPolicy
  noise_type: ornstein-uhlenbeck
  noise_std: 0.5
  gradient_steps: 1
  train_freq: 1
  learning_rate: 0.001
  batch_size: 256
  policy_kwargs: dict(net_arch=[32, 32])
